Fix #115 Concurrency issue when adding documents.
FoundatioFx/Foundatio.Repositories pull request #116
Opened 2024-12-23 19:10 UTC by niemyjski

2024-12-23 19:10 UTC, niemyjski commented on src/Foundatio.Repositories.Elasticsearch/Configuration/DailyIndex.cs
> +        await using var indexLock = await _ensureIndexLock.AcquireAsync($"Index:{Name}", TimeSpan.FromMinutes(1)).AnyContext();
Not in love with this lock name but it works.

2024-12-23 19:16 UTC, niemyjski commented on src/Foundatio.Repositories.Elasticsearch/Configuration/DailyIndex.cs
> +        await using var indexLock = await _ensureIndexLock.AcquireAsync($"Index:{GetVersionedIndex(utcDate.Date)}", TimeSpan.FromMinutes(1)).AnyContext();
not in love that some date logic and this index name gets created after this, but felt like this needed to happen like this for the lock

2024-12-24 12:14 UTC, niemyjski commented on src/Foundatio.Repositories.Elasticsearch/Configuration/DailyIndex.cs
> +        await using var indexLock = await _ensureIndexLock.AcquireAsync($"Index:{GetVersionedIndex(utcDate)}", TimeSpan.FromMinutes(1)).AnyContext();
It kind of feels like we should be locking on the index name here, but this allows us to go wide. I'm wondering if we should also change this to a concurrent dictionary.

2025-01-01 01:34 UTC, ejsmith commented on src/Foundatio.Repositories.Elasticsearch/Configuration/DailyIndex.cs
> +            throw new Exception("Unable to acquire index lock");
We should check to see if another process created the index we are looking for instead of just throwing here.

2025-01-01 01:36 UTC, ejsmith approved these changes
I like this change. Should be good.

2025-01-01 01:38 UTC, ejsmith requested changes
Actually, just thought about something. DailyIndex should be a singleton. Couldn't we just change the _ensuredDates to be a concurrent dictionary and not do a distributed lock?

2025-01-02 14:18 UTC, niemyjski commented
@ejsmith I thought about that, we probably could. That's making assumptions it is registered as a singleton and then there is alias management going on. Seems safer to do it like this.

2025-01-02 14:56 UTC, ejsmith commented
There would actually be a single instance per daily index and we can count on that because that's how it has to be registered for a daily index to work. So I think just changing to a concurrent dictionary would work and is what we want to do.

2025-01-02 14:57 UTC, ejsmith commented
There are just multiple threads trying to ensure an index for a specific day at the same time. Which is what the error you are seeing is from.

2025-01-06 21:24 UTC, merged

2025-01-06 21:27 UTC, ejsmith reviewed
Looks good